Add script to check whether the newly built archive is an extension of the previous one
input-output-hk/cardano-haskell-packages pull request #75
Opened 2022-10-26 13:17 UTC by michaelpj

I didn't have time to set this up in the GHA, it's changed a bit and I'm not sure what's going on right now. Maybe you can take a look @andreabedini ?

I tested this a bit and it seems to do the job. I tried:
- Adding a package with an old timestamp (BAD)
- Adding a package with a new timestamp (GOOD)
- Removing a package (BAD)
- Changing the timestamp of a package (BAD)

2022-10-27 01:59 UTC, andreabedini commented on scripts/check-archive-extension.sh
> +OLD_LISTING=$(tar -tvf "$OLD_INDEX_TAR" | sort -k4,5)
Sorting should not be needed because foliage always write the tarball entries in order of their timestamp.

This also simplifies things since if tarball A is a prefix of tarball B (as a list of bytes) then it's implied that all entries of tarball B have greater timestamp of all entries of tarball A. :thought_balloon: minus perhaps the edge case where the last timestamp of A is the same as the first timestamp of B :thinking:

2022-10-27 02:04 UTC, andreabedini commented on scripts/check-archive-extension.sh
> +if [[ $LAST_OLD_DATE > $FIRST_ACTUALLY_NEW_DATE ]]; then
I am tempted to put a `>=` here. Foliage at the moment only orders by timestamp but doesn't guarantee any order within the same timestamp. So you could add a new package with the exact same timestamp as the last one and it might get inserted just before, violating the append-only guarantee. I can make foliage give more guarantees about the ordering but I think it's a good idea to be stricter here in what we allow.

2022-10-27 02:07 UTC, andreabedini requested changes
This is a good start. We are not checking the first tarball is a prefix of the second though. This check would subsumes some of the checks we do. That said, the checks you are suggesting offer good feedback, and we should keep them all anyway.

- You can assume the tarball is in timestamp order, this might simplify something
- `$LAST_OLD_DATE > $FIRST_ACTUALLY_NEW_DATE` as commented I think we should be stricter here
- Keen to add a byte-wise-comparison

2022-10-27 08:15 UTC, michaelpj commented on scripts/check-archive-extension.sh
> +OLD_LISTING=$(tar -tvf "$OLD_INDEX_TAR" | sort -k4,5)
So, I tried to compare them as lists of bytes with `cmp`, but even when they were prefixes wrt entries `cmp` did not think that they were prefixes wrt bytes. Which is annoying, perhaps due to the binary structure of tar files. I figured this was easier than trying to figure that out!

(Also, sorting is cheap and robust, so why not?)

2022-10-27 08:16 UTC, michaelpj commented on scripts/check-archive-extension.sh
> +if [[ $LAST_OLD_DATE > $FIRST_ACTUALLY_NEW_DATE ]]; then
Sounds good.

2022-10-27 08:18 UTC, michaelpj commented
> Keen to add a byte-wise-comparison

Yeah, as I said above this is what I tried first but I couldn't make it work. Here's roughly what I tried:

```
cmp -n "$(wc -c < archive-1)" archive-1 archive-2
```
i.e. compare the two up to the length of the first one. I think that should return true if the first one is a prefix of the second one, byte-wise. But generally it didn't work: there would be differences some way before the end of the first file.

2022-10-27 08:19 UTC, michaelpj commented
"A tar file is terminated by two blocks of zero bytes" that would do it...

2022-10-27 08:51 UTC, andreabedini commented on scripts/check-archive-extension.sh
> +OLD_LISTING=$(tar -tvf "$OLD_INDEX_TAR" | sort -k4,5)
It would work but I'll have a go myself (tomorrow)

2022-10-27 13:17 UTC, michaelpj commented
Pushed a few changes.

2022-11-01 14:30 UTC, michaelpj commented
I figured out that of course, if the archive is predictably terminated by two blocks of size 512, I can just compare up to `length - 1024` bytes, which works nicely. Now this checks for byte-wise extension, and if that fails it goes through the other checks to try and give a better reason for why it's wrong.

2022-11-01 16:28 UTC, michaelpj commented
Have a look at the script change, but I'd like to try and get at least a basic CI check using it in this PR. I'm trying to just rebuild the base of the PR with the same keys and then compare them, that should be a reasonable check for a PR.

2022-11-02 04:09 UTC, andreabedini commented
`nix develop -c foliage create-keys` has failed because now the checkout is in `./base` and `./tip`. Perhaps it's worth using a single checkout and the cache.

Perhaps we can do something like

```
- uses: actions/checkout@v3 # we might need to add `fetch-depth: 0` or any largish number
- git checkout --detach ${{github.base_ref}}
- nix develop -c foliage build
- mv _repo _repo_base
- git checkout --detach ${{github.head_ref}}
- nix develop -c foliage build
- # compare _repo _repo_base
```

?

2022-11-03 04:30 UTC, andreabedini commented
> Okay, I think it works on PRs! I'd like to also run it on deploy, but I need to figure out what's going on there. I'm not sure it's _actually_ checking out the repo branch?

The deploy step deploys the `built-repo` artifact created by the build step, it doesn't recreate it. The `action/checkout` is because we also commit the repository to the repo branch. A bit of some wizardry there perhaps but the tl;dr; is "commit this folder _repo on top of the repo branch".

2022-11-03 04:31 UTC, andreabedini approved these changes

2022-11-03 11:25 UTC, michaelpj commented
> The deploy step deploys the built-repo artifact created by the build step, it doesn't recreate it.

Right, but the reason I want to run it on deploy is because the check that's running in `build` is currently running against a newly created repository, not the one in `repo`. _Conceivably_ they might be different, better to be safe and do it again.

> A bit of some wizardry there perhaps

Yeah, I just need to figure out a way to also get the existing version so I can check against it. I think at the moment you never do that, and you just push a new commit with the new version.

2022-11-03 12:33 UTC, andreabedini commented on .github/workflows/CI.yml
> +          ./src/scripts/check-archive-extension.sh repo/01-index.tar built-repo/01-index.tar
Twice for good measure? :joy:

2022-11-03 23:29 UTC, andreabedini commented
It looks very clean now! Awesome work.

2022-11-04 10:22 UTC, merged