Start a CODEOWNERS file
input-output-hk/cardano-haskell-packages pull request #92
Opened 2022-11-11 14:51 UTC by michaelpj

I think this is a reasonably sane way to do access control. As a trial, I'm just going to set it up to request reviews from the listed people, but not to require them. We may want to make it a requirement in future.

Thus far I've added what I think is correct for `plutus`, `ledger`, `ouroboros-consensus`, and the patched pacakges. I don't know who or what to put for `cardano-node`, ideally there would be a team (Jordan?).

It would be great to find people for the other repositories in here.

I've also added some commentary to the README suggesting when people should add themselves to CODEOWNERS.

Work towards #33.

@disassembler maybe the release team should also be listed everywhere?
@coot I added the teams that are listed in the `ouroboros-network` CODEOWNERS but I can't find them anywhere and I can't give them write access here, so I think what's there currently won't work.

2022-11-11 15:15 UTC, Jimbo4350 commented
@michaelpj  I would put myself, Sam and John Ky for cardano-node

2022-11-11 15:20 UTC, michaelpj commented
@Jimbo4350 could you start a `cardano-node` team for that? I think it's a lot easier to maintain if it's a team rather than a list of individuals.

2022-11-11 16:17 UTC, zliu41 commented
@input-output-hk/plutus is very big and includes both Plutus Core and Tools and more. I don't see the need to request reviews from all of them for every PR.

2022-11-11 16:19 UTC, michaelpj commented
Yes, I should remove the tools people. But I think it's the most sensible team to use here, no?

2022-11-11 16:21 UTC, zliu41 commented
Yeah or just split it into two teams, since "plutus" isn't really a thing :smile:

2022-11-11 21:02 UTC, coot requested changes

2022-11-11 21:02 UTC, coot commented on CODEOWNERS
> +_sources/cardano-client                     @input-output-hk/network-superowners
```suggestion
_sources/io-sim                             @input-output-hk/ouroboros-networking
_sources/io-sim-classes                     @input-output-hk/ouroboros-networking
_sources/network-mux                        @input-output-hk/ouroboros-networking
_sources/ntp-client                         @input-output-hk/ouroboros-networking
_sources/typed-protocols                    @input-output-hk/ouroboros-networking
_sources/typed-protocols-examples           @input-output-hk/ouroboros-networking
_sources/Win32-network                      @input-output-hk/ouroboros-networking
_sources/ouroboros-network-framework        @input-output-hk/ouroboros-networking 
_sources/ouroboros-network                  @input-output-hk/ouroboros-networking 
_sources/ouroboros-network/wireshark-plugin @input-output-hk/ouroboros-networking 
_sources/ouroboros-network-testing          @input-output-hk/ouroboros-networking 
_sources/cardano-client                     @input-output-hk/ouroboros-networking 
```

2022-11-11 21:03 UTC, coot commented on CODEOWNERS
> +_sources/cardano-client                     @input-output-hk/network-superowners
[ouroboros-networking](https://github.com/orgs/input-output-hk/teams/ouroboros-networking) group.

2022-11-11 21:05 UTC, JaredCorduan approved these changes
:+1:

2022-11-12 01:48 UTC, andreabedini approved these changes
This is great.

2022-11-12 01:50 UTC, andreabedini commented
Notice that, as it stands, GitHub complains. This might be fixed by @coot's suggestions above.
```
Unknown owner on line 39: make sure the team @input-output-hk/network-superowners exists and has write access to the repository
```

2022-11-12 09:57 UTC, coot commented on CODEOWNERS
> +_sources/ouroboros-consensus-cardano-test/  @input-output-hk/consensus-superowners
@dnadales, @nfrisby  I suspect these should be `@input-output-hk/ouroboros-consensus`

2022-11-14 10:11 UTC, michaelpj commented on CODEOWNERS
> +_sources/ouroboros-consensus-cardano-test/  @input-output-hk/consensus-superowners
Changed to that, that does indeed seem to be the public team.

2022-11-14 10:15 UTC, michaelpj commented
Updated. I think we can start with this. @Jimbo4350 @disassembler let me know as and when you want to add more stuff to this.

2022-11-14 10:15 UTC, merged